{
 "title": "Energy Monitor",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ET1", "query": ".26533" },
   { "name": "ET2", "query": ".27743" },
   { "name": "GAS", "query": "1.00631" },
   { "name": "GAS_KWH_M3", "query": "11.70" },
   { "name": "query0", "label": "V", "query": "1" }
  ]
 },
 "panels": [
  {
   "title": "Real-time consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "consumption",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "p1data",
     "select": [
      [
       { "params": [ "power_delivered_w" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "p1data",
     "select": [
      [
       { "params": [ "power_delivered_w" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electricity Consumption /h",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "p1data",
     "query": "SELECT derivative(\"energy_t1\", $__interval) FROM \"p1\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "energy_t1" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Valley" ], "type": "alias" }
      ],
      [
       { "params": [ "energy_t2" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Peak" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "p1data",
     "select": [
      [
       { "params": [ "energy_t1" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Valley" ], "type": "alias" }
      ],
      [
       { "params": [ "energy_t2" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Peak" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electricity Usage in Interval",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "measurement": "p1data",
     "query": "SELECT \"dalverbruik\", \"piekverbruik\" FROM \"p1data\" WHERE $timeFilter AND dalverbruik != -1 and piekverbruik != -1 ORDER BY time DESC",
     "select": [
      [
       { "params": [ "energy_t1" ], "type": "field" }
      ],
      [
       { "params": [ "energy_t2" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas consumption per hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "alias": "Gas",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "p1data",
     "query": "SELECT derivative(mean(\"gas\"), 1h) * 1000 FROM \"p1data\" WHERE $timeFilter AND gas != -1 GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "gas" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Gas Consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "p1data",
     "select": [
      [
       { "params": [ "gas" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Gas" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas Usage in Interval",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "measurement": "p1data",
     "query": "SELECT \"gas\" FROM \"p1data\" WHERE \"gas\" != -1 AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "gas" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "Current",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "p1data",
     "select": [
      [
       { "params": [ "current_delivered" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tariff",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "tariff",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "tariff" ], "type": "tag" }
     ],
     "measurement": "p1data",
     "select": [
      [
       { "params": [ "power_delivered_w" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cost (grouped by h)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "p1data",
     "query": "SELECT max(\"tariff_indicator\") AS \"tariff\", difference(mean(\"energy_t1\")) * $T1, difference(mean(\"energy_t2\")) * $T2 FROM \"p1\" WHERE (\"tariff\" = '1') AND $timeFilter GROUP BY time(30m) fill(null)",
     "select": [
      [
       { "params": [ "energy_t1" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "* $ET1" ], "type": "math" },
       { "params": [ "Valley" ], "type": "alias" }
      ],
      [
       { "params": [ "energy_t2" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "* $ET2" ], "type": "math" },
       { "params": [ "Peak" ], "type": "alias" }
      ],
      [
       { "params": [ "gas" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "* $GAS" ], "type": "math" },
       { "params": [ "Gas" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Energy spent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "p1data",
     "query": "SELECT max(\"tariff_indicator\") AS \"tariff\", difference(mean(\"energy_t1\")) * $T1, difference(mean(\"energy_t2\")) * $T2 FROM \"p1\" WHERE (\"tariff\" = '1') AND $timeFilter GROUP BY time(30m) fill(null)",
     "select": [
      [
       { "params": [ "energy_t1" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Valley" ], "type": "alias" }
      ],
      [
       { "params": [ "energy_t2" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Peak" ], "type": "alias" }
      ],
      [
       { "params": [ "gas" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "* $GAS_KWH_M3" ], "type": "math" },
       { "params": [ "Gas" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}